[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
serde = "1.0.219"
serde_json = "1.0.140"
json-web-token = "0.2.0"
dotenvy = "0.15.7"
diesel = {version = "2.0", features = ["serde_json", "r2d2", "Uuid", "postgres"] }
