import type { Metadata } from "next";
import GlobalStyle from "@/global-style";
import TabBar from "@/layouts/tab-bar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
    <GlobalStyle/>
      <body>
        {children}
        <TabBar/>
      </body>
    </html>
  );
}
