name: CI for Front-end

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_front_end:
    runs-on: ubuntu-latest
    working-directory: ./webapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install depedencies
        run: npm i

      - name: Run linting
        run: npm run lint

      - name: Build Next.js project
        run: npm run build
